### ISSUE TITLE
Feedback from group C

### ISSUE THREAD

**Issue by Whitesheep18** [gustavjohansen98/E-vil-Corp#81]
1. Chrome detected that my password was exposed on the site when I registered. I didn't look into it, but that seems like a serious issue.
2. I can't share. I can write to the form but when I click "share" nothing happens. I'm not sure if it registers my message, because the message is not displayed on my timeline.
3. The application freezes sometimes. I can click on links but nothing happens. I could induce it a couple of times by signing out and signing in again.
+. The little things:
  a) The tab is not named after the page, but is always "mvp"
  b) I see '//' in my timeline. I assume it wanted to be a flash message...
  c) loading messages on the public timeline takes a second. It's a bit like it doesn't directly redirect to the right page

Other than these, great job!

**Comment by LVOL98** [comment]
Thank you for the great feedback, we're on it. Don't know about point 1, maybe it has to do with the connection being unsecure

**Comment by LVOL98** [comment]
Fixed the problem of messages not being tweeted

**Comment by LVOL98** [comment]
Fixed the problem of //

**Comment by LVOL98** [comment]
Removed the security breach warning by using a more efficient hasher
